### ISSUE TITLE
Add Dark Mode Toggle to Enhance User Experience

### ISSUE THREAD

**Issue by hansoinner** [hansoinner/todolist#4]
### Objective
The primary goal is to introduce a dark mode toggle, allowing users to switch between light and dark themes based on their preference or ambient lighting conditions. This enhancement aims to improve user experience, reduce eye strain, and align our application with modern design standards.

### Feature Details
- **Dark Mode Toggle**: A user-friendly switch, accessible from the main interface, enabling users to easily toggle between light and dark themes.
- **Theme Persistence**: The selected theme should persist across sessions, remembering the user's preference.
- **Automatic Mode (Optional)**: Consider an automatic mode where the application detects the system's theme settings and adjusts accordingly.
- **UI Consistency**: Ensure that all UI elements are clearly visible and aesthetically pleasing in both modes.
- **Accessibility Compliance**: The dark mode should comply with accessibility standards, ensuring readability and usability for all users.

### Benefits
- **Enhanced User Comfort**: Reduces glare and eye strain, particularly in low-light environments.
- **Personalization**: Offers users the flexibility to choose a theme that suits their preferences or needs.
- **Battery Efficiency**: On devices with OLED or AMOLED screens, dark mode can contribute to battery saving.
- **Modernization**: Keeps the application in line with current design trends and user expectations.

### Implementation Considerations
- Evaluate the current color palette and design elements for compatibility with dark mode.
- Ensure cross-platform consistency in appearance and functionality.
- Test for readability, usability, and overall user experience across various devices and screen sizes.

**Comment by Miltonbhowmick** [comment]
Hello @hansoinner,
Is there any preferable color palette you choose in past?
